version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/hydro-elastic
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/hydro-oicq
    schedule:
      interval: daily
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
