version: "3.9"

services:
  oj-mongo:
    image: mongo:4-focal
    container_name: oj-mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
      - ./data/backup:/dump

  # oj-elastic:
  #   image: elasticsearch:8.2.0
  #   container_name: oj-elastic
  #   restart: always
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   environment:
  #     - discovery.type=single-node
  #     - ES_SETTING_XPACK_SECURITY_ENABLED=false

  oj-backend:
    image: stagoh/jgsuoj-backend
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-mongo
      # - oj-elastic
    volumes:
      - ./config/backend:/root/.hydro
      - ./data/file:/data/file
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.utf8
    ports:
      - "0.0.0.0:80:8888"

  oj-judge:
    image: stagoh/jgsuoj-judge
    container_name: oj-judge
    restart: always
    privileged: true
    shm_size: 1536mb
    volumes:
      - ./config/judge:/root/.config/hydro

# volumes:
#   esdata:
