version: "3.9"

services:
  oj-minio:
    image: minio/minio
    container_name: oj-minio
    command: server /data
    restart: always
    volumes:
      - ./data/dev/minio:/data
    ports:
      - 9000:9000

  oj-mongo:
    image: mongo:4-focal
    container_name: oj-mongo
    restart: always
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - 27017:27017

  oj-elastic:
    image: elasticsearch:8.2.0
    container_name: oj-elastic
    restart: always
    volumes:
      - esdata_dev:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_SETTING_XPACK_SECURITY_ENABLED=false
    ports:
      - 9200:9200

volumes:
  esdata_dev:
