version: '3.7'

services:
  oj-minio:
    image: minio/minio
    container_name: oj-minio-test
    command: server /data
    restart: always
    volumes:
      - ./data/test/minio:/data

  oj-mongo:
    image: mongo:4-focal
    container_name: oj-mongo-test
    restart: always
    volumes:
      - ./data/test/mongo:/data/db

  oj-sonic:
    image: valeriansaliou/sonic:v1.3.2
    container_name: oj-sonic-test
    restart: always
    volumes:
      - ./data/test/sonic:/data/store
      - ./config/sonic/sonic.cfg:/etc/sonic.cfg

  oj-backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile-test
    container_name: oj-backend-test
    restart: always
    depends_on:
      - oj-minio
      - oj-mongo
      - oj-sonic
    volumes:
      - ./config/backend:/root/.hydro
    ports:
      - "0.0.0.0:80:8888"

  oj-judge:
    build:
      context: ..
      dockerfile: docker/judge/Dockerfile-test
    container_name: oj-judge-test
    restart: always
    privileged: true
    volumes:
      - ./config/judge:/root/.config/hydro
    shm_size: '1536mb'
