version: "3.9"

services:
  oj-minio:
    image: minio/minio
    container_name: oj-minio
    command: server /data
    restart: always
    volumes:
      - ./data/test/minio:/data

  oj-mongo:
    image: mongo:4-focal
    container_name: oj-mongo
    restart: always
    volumes:
      - ./data/test/mongo:/data/db

  oj-elastic:
    image: elasticsearch:8.2.0
    container_name: oj-elastic
    restart: always
    volumes:
      - esdata_test:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_SETTING_XPACK_SECURITY_ENABLED=false

  oj-backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-minio
      - oj-mongo
      - oj-elastic
    volumes:
      - ./config/backend:/root/.hydro
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.utf8
    ports:
      - "0.0.0.0:80:8888"

  oj-judge:
    build:
      context: ..
      dockerfile: docker/judge/Dockerfile
    container_name: oj-judge
    restart: always
    privileged: true
    shm_size: 1536mb
    volumes:
      - ./config/judge:/root/.config/hydro

volumes:
  esdata_test:
