version: '3.7'

services:
  oj-minio:
    image: minio/minio
    container_name: oj-minio
    command: server /data
    restart: always
    volumes:
      - ./data/minio:/data

  oj-mongo:
    image: mongo:4-focal
    container_name: oj-mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
      - ./data/backup:/dump

  # oj-sonic:
  #   image: valeriansaliou/sonic:v1.3.2
  #   container_name: oj-sonic
  #   restart: always
  #   volumes:
  #     - ./data/sonic:/data/store
  #     - ./config/sonic/sonic.cfg:/etc/sonic.cfg

  oj-backend:
    image: registry.cn-hangzhou.aliyuncs.com/jgsu-acm/backend
    container_name: oj-backend
    restart: always
    depends_on:
      - oj-minio
      - oj-mongo
      # - oj-sonic
    volumes:
      - ./config/backend:/root/.hydro
    ports:
      - "0.0.0.0:80:8888"

  oj-judge:
    image: registry.cn-hangzhou.aliyuncs.com/jgsu-acm/judge
    container_name: oj-judge
    restart: always
    privileged: true
    depends_on:
      - oj-backend
    volumes:
      - ./config/judge:/root/.config/hydro
    shm_size: '1536mb'
