version: '3.8'

services:
  hydro:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ..:/workspace:cached
      - .hydro:/root/.hydro
      - testdata:/data/file
      - ~/.ssh:/root/.ssh

  mongo:
    image: mongo:4-focal
    restart: unless-stopped
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
  testdata:
