version: '3.8'

services:
  hydro:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ..:/workspace:cached
      - testdata:/data/file

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodata:/data/db

  elastic:
    image: elasticsearch:8.2.0
    restart: unless-stopped
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_SETTING_XPACK_SECURITY_ENABLED=false

volumes:
  mongodata:
  esdata:
  testdata:
