version: "3.9"

services:
  mongo:
    image: mongo:4-focal
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
  hydro:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    depends_on:
      - mongo
    volumes:
      - ..:/workspace:cached
      - cfgdata:/home/node/.hydro:rw
      - testdata:/data/file:rw
      - ~/.gitconfig:/home/node/.gitconfig:ro
      - ~/.ssh:/home/node/.ssh:ro

volumes:
  mongodata:
  cfgdata:
  testdata:
