Coding:
  - name: C/C++
  - name: Java
  - name: Python
  - name: JavaScript/TypeScript
  - name: Markdown
  - name: LaTeX
  - name: 其他语言
算法竞赛:
  - name: 算法
  - name: 数据结构
  - name: 图论
  - name: 数学
  - name: 博弈论
  - name: 其他知识
比赛:
  - name: 实验室比赛
  - name: ICPC
  - name: CCPC
  - name: 蓝桥杯
  - name: 其他比赛
OJ:
  - name: Hydro
  - name: 洛谷
  - name: CodeForces
  - name: ATCoder
  - name: 其他OJ
实验室相关:
  - name: 通知
  - name: 日程
  - name: 其他信息