模拟: []
贪心: []
递归: []
递推:
  - 光速幂
前缀和: []
差分: []
离散化: []
双指针: []
DFS: []
BFS: []
排序: []
构造: []
打表: []
位运算: []
高精度: []
倍增:
  - ST表
随机化:
  - 模拟退火
哈希:
  - 字符串哈希
  - 树哈希
分块:
  - 莫队
  - Sqrt Tree
枚举:
  - 排列枚举
  - 子集枚举
  - 二分答案
分治:
  - 快速幂
  - CDQ分治
  - 二分搜索
  - 三分搜索
  - 整体二分
搜索:
  - 双向搜索
  - 剪枝
  - A*/IDA*
  - DLX
  - 回溯
动态规划:
  - 背包DP
  - 区间DP
  - 划分DP
  - 数位DP
  - 状压DP
  - 树上DP
  - DAG上DP
  - 插头DP
  - 动态DP
  - 概率DP
  - 单调队列/栈优化
  - 矩阵加速
  - 斜率优化
  - 平行四边形优化
  - 滚动数组
树:
  - 二叉树
  - DFS序
  - 欧拉序
  - 括号序
  - 树的直径
  - LCA
  - 树上倍增
  - 树上差分
  - 树链剖分
  - dsu on tree
  - 虚树
  - 树的重心
  - 点分治
  - 边分治
  - 动态树分治
图论:
  - DAG
  - 拓扑排序
  - 差分约束
  - 矩阵树定理
  - 最小生成树
  - 次小生成树
  - 单源最短路径
  - 全源最短路径
  - 负环
  - K短路
  - 强连通分量
  - 双连通分量
  - 割点
  - 桥
  - 缩点
  - 最小树形图
  - 独立集
  - 覆盖集
  - 最大匹配
  - 二分图
  - 圆方树
  - 2-SAT
  - 欧拉图
  - 哈密顿图
  - 最大流
  - 最小割
  - 费用流
  - 上下界网络流
数据结构:
  - 链表
  - 队列
  - 栈
  - 堆
  - 并查集
  - 树状数组
  - 线段树
  - 主席树
  - 划分树
  - 线段树分裂合并
  - 平衡树
  - 可持久化平衡树
  - 树套树
  - 左偏树
  - 可持久化左偏树
  - Link Cut Tree
  - 单调队列
  - 单调栈
  - K-D Tree
  - Kruskal重构树
  - 笛卡尔树
  - 0-1 Trie
  - 可持久化0-1 Trie
字符串:
  - KMP
  - 扩展KMP
  - Manacher
  - Trie
  - 自动机
  - AC自动机
  - 回文自动机
  - 后缀自动机
  - 后缀树
  - 后缀树组
博弈论:
  - 巴什博弈
  - Nim博弈
  - 威佐夫博弈
  - 斐波那契博弈
  - SG定理
数学:
  - 斐波那契数列
  - 复数
  - 高等数学
  - 概率论
  - 线性规划
  - 生成函数
  - FFT
  - FWT
  - NTT
线性代数:
  - 矩阵
  - 高斯消元
  - 线性基
数论:
  - 线性筛/欧拉筛
  - 埃氏筛
  - Min-25筛
  - 杜教筛
  - 欧拉函数
  - 欧拉定理
  - 扩展欧拉定理
  - 费马小定理
  - GCD
  - 扩展欧几里得
  - 质因数分解
  - 中国剩余定理
  - 扩展中国剩余定理
  - 逆元
  - 同余
  - BSGS
  - 扩展BSGS
  - 数论分块
  - 狄利克雷前缀和
  - 莫比乌斯反演
  - 裴蜀定理
  - 卢卡斯定理
  - 二次剩余
  - 线性同余方程
组合数学:
  - 加法原理 
  - 乘法原理
  - 杨辉三角
  - 排列组合
  - 斯特林数
  - 卡特兰数
  - 容斥原理
  - 抽屉原理
  - 康托展开
多项式:
  - 自然数幂和
  - 拉格朗日插值
  - FFT
  - NTT
  - FWT
  - 多项式除法
  - 多项式开方
  - 多项式exp
  - 多项式ln
  - 多项式多点求值
  - 多项式快速插值
  - 多项式求逆
  - 多项式快速幂
计算几何:
  - 扫描线
  - 平面最近点对
  - 几何图形的交与并
  - 凸包
  - 旋转卡壳
  - 半平面交
  - 反演
  - 三角剖分
  - 梯形剖分
