name: Create and publish a Docker image

on:
  push:
    branches: [ 'master' ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@7f47463f5646678eb7ccf8f0f2e2d0896916a10a
        with:
          username: stagoh
          password: ${{ secrets.DH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: b_meta
        uses: docker/metadata-action@a287d15e54221320e8a1b9d1a4bb26519678d2c3
        with:
          images: stagoh/backend
      
      - name: Extract metadata (tags, labels) for Docker
        id: j_meta
        uses: docker/metadata-action@a287d15e54221320e8a1b9d1a4bb26519678d2c3
        with:
          images: stagoh/judge

      - name: Build and push Docker image 
        uses: docker/build-push-action@5e11b373bfed0d8024ef33d1586c675819690e95
        with:
          context: docker/judge
          push: true
          tags: ${{ steps.b_meta.outputs.tags }}
          labels: ${{ steps.b_meta.outputs.labels }}

      - name: Build and push Docker image ( Dev )
        uses: docker/build-push-action@5e11b373bfed0d8024ef33d1586c675819690e95
        with:
          context: docker/backend
          push: true
          tags: ${{ steps.j_meta.outputs.tags }}
          labels: ${{ steps.j_meta.outputs.labels }}